/**
 * Countries sorted by area (largest to smallest)
 * Used for assigning countries to projects based on volume rankings
 * Top 194 projects get countries, with #1 volume getting the biggest country
 * 
 * Data extracted from Natural Earth GeoJSON and sorted by area
 */

export interface Country {
  iso: string; // ISO 3166-1 alpha-2 code
  name: string;
  area: number; // Area in square kilometers
}

/**
 * Countries sorted by area (largest to smallest)
 * This list contains 194+ countries for the top 194 projects
 */
export const countriesBySize: Country[] = [
  { iso: 'RU', name: 'Russia', area: 17098242 },
  { iso: 'CA', name: 'Canada', area: 9984670 },
  { iso: 'CN', name: 'China', area: 9596961 },
  { iso: 'US', name: 'United States', area: 9525067 },
  { iso: 'BR', name: 'Brazil', area: 8514877 },
  { iso: 'AU', name: 'Australia', area: 7692024 },
  { iso: 'IN', name: 'India', area: 3287263 },
  { iso: 'AR', name: 'Argentina', area: 2780400 },
  { iso: 'KZ', name: 'Kazakhstan', area: 2724900 },
  { iso: 'DZ', name: 'Algeria', area: 2381741 },
  { iso: 'CD', name: 'Democratic Republic of the Congo', area: 2344858 },
  { iso: 'SA', name: 'Saudi Arabia', area: 2149690 },
  { iso: 'MX', name: 'Mexico', area: 1964375 },
  { iso: 'ID', name: 'Indonesia', area: 1904569 },
  { iso: 'SD', name: 'Sudan', area: 1861484 },
  { iso: 'LY', name: 'Libya', area: 1759540 },
  { iso: 'IR', name: 'Iran', area: 1648195 },
  { iso: 'MN', name: 'Mongolia', area: 1564110 },
  { iso: 'NG', name: 'Nigeria', area: 923768 },
  { iso: 'PE', name: 'Peru', area: 1285216 },
  { iso: 'TD', name: 'Chad', area: 1284000 },
  { iso: 'NE', name: 'Niger', area: 1267000 },
  { iso: 'AO', name: 'Angola', area: 1246700 },
  { iso: 'ML', name: 'Mali', area: 1240192 },
  { iso: 'ZA', name: 'South Africa', area: 1221037 },
  { iso: 'CO', name: 'Colombia', area: 1141748 },
  { iso: 'ET', name: 'Ethiopia', area: 1104300 },
  { iso: 'BO', name: 'Bolivia', area: 1098581 },
  { iso: 'MR', name: 'Mauritania', area: 1030700 },
  { iso: 'EG', name: 'Egypt', area: 1001449 },
  { iso: 'TZ', name: 'Tanzania', area: 947300 },
  { iso: 'VE', name: 'Venezuela', area: 916445 },
  { iso: 'PK', name: 'Pakistan', area: 881912 },
  { iso: 'NA', name: 'Namibia', area: 824292 },
  { iso: 'MZ', name: 'Mozambique', area: 801590 },
  { iso: 'TR', name: 'Turkey', area: 783562 },
  { iso: 'CL', name: 'Chile', area: 756102 },
  { iso: 'ZM', name: 'Zambia', area: 752612 },
  { iso: 'MM', name: 'Myanmar', area: 676578 },
  { iso: 'BW', name: 'Botswana', area: 582000 },
  { iso: 'AF', name: 'Afghanistan', area: 652230 },
  { iso: 'SO', name: 'Somalia', area: 637657 },
  { iso: 'CF', name: 'Central African Republic', area: 622984 },
  { iso: 'SS', name: 'South Sudan', area: 619745 },
  { iso: 'UA', name: 'Ukraine', area: 603500 },
  { iso: 'MG', name: 'Madagascar', area: 587041 },
  { iso: 'KE', name: 'Kenya', area: 580367 },
  { iso: 'FR', name: 'France', area: 551695 },
  { iso: 'YE', name: 'Yemen', area: 527968 },
  { iso: 'TH', name: 'Thailand', area: 513120 },
  { iso: 'ES', name: 'Spain', area: 505990 },
  { iso: 'TM', name: 'Turkmenistan', area: 488100 },
  { iso: 'CM', name: 'Cameroon', area: 475442 },
  { iso: 'PG', name: 'Papua New Guinea', area: 462840 },
  { iso: 'SE', name: 'Sweden', area: 450295 },
  { iso: 'UZ', name: 'Uzbekistan', area: 447400 },
  { iso: 'MA', name: 'Morocco', area: 446550 },
  { iso: 'IQ', name: 'Iraq', area: 438317 },
  { iso: 'PY', name: 'Paraguay', area: 406752 },
  { iso: 'ZW', name: 'Zimbabwe', area: 390757 },
  { iso: 'JP', name: 'Japan', area: 377975 },
  { iso: 'DE', name: 'Germany', area: 357114 },
  { iso: 'CG', name: 'Republic of the Congo', area: 342000 },
  { iso: 'FI', name: 'Finland', area: 338424 },
  { iso: 'VN', name: 'Vietnam', area: 331212 },
  { iso: 'MY', name: 'Malaysia', area: 330803 },
  { iso: 'NO', name: 'Norway', area: 323802 },
  { iso: 'CI', name: 'Ivory Coast', area: 322463 },
  { iso: 'PL', name: 'Poland', area: 312696 },
  { iso: 'OM', name: 'Oman', area: 309500 },
  { iso: 'IT', name: 'Italy', area: 301340 },
  { iso: 'PH', name: 'Philippines', area: 300000 },
  { iso: 'EC', name: 'Ecuador', area: 283561 },
  { iso: 'BF', name: 'Burkina Faso', area: 274200 },
  { iso: 'NZ', name: 'New Zealand', area: 270467 },
  { iso: 'GA', name: 'Gabon', area: 267668 },
  { iso: 'GN', name: 'Guinea', area: 245857 },
  { iso: 'GB', name: 'United Kingdom', area: 242900 },
  { iso: 'UG', name: 'Uganda', area: 241550 },
  { iso: 'GH', name: 'Ghana', area: 238533 },
  { iso: 'RO', name: 'Romania', area: 238397 },
  { iso: 'LA', name: 'Laos', area: 236800 },
  { iso: 'GY', name: 'Guyana', area: 214969 },
  { iso: 'BY', name: 'Belarus', area: 207600 },
  { iso: 'KG', name: 'Kyrgyzstan', area: 199951 },
  { iso: 'SN', name: 'Senegal', area: 196722 },
  { iso: 'SY', name: 'Syria', area: 185180 },
  { iso: 'KH', name: 'Cambodia', area: 181035 },
  { iso: 'UY', name: 'Uruguay', area: 176215 },
  { iso: 'SR', name: 'Suriname', area: 163820 },
  { iso: 'TN', name: 'Tunisia', area: 163610 },
  { iso: 'BD', name: 'Bangladesh', area: 147570 },
  { iso: 'NP', name: 'Nepal', area: 147181 },
  { iso: 'TJ', name: 'Tajikistan', area: 143100 },
  { iso: 'GR', name: 'Greece', area: 131957 },
  { iso: 'NI', name: 'Nicaragua', area: 130373 },
  { iso: 'ER', name: 'Eritrea', area: 117600 },
  { iso: 'KP', name: 'North Korea', area: 120538 },
  { iso: 'MW', name: 'Malawi', area: 118484 },
  { iso: 'BJ', name: 'Benin', area: 112622 },
  { iso: 'HN', name: 'Honduras', area: 112492 },
  { iso: 'LR', name: 'Liberia', area: 111369 },
  { iso: 'BG', name: 'Bulgaria', area: 110879 },
  { iso: 'CU', name: 'Cuba', area: 109884 },
  { iso: 'GT', name: 'Guatemala', area: 108889 },
  { iso: 'IS', name: 'Iceland', area: 103000 },
  { iso: 'KR', name: 'South Korea', area: 100210 },
  { iso: 'HU', name: 'Hungary', area: 93028 },
  { iso: 'PT', name: 'Portugal', area: 92090 },
  { iso: 'JO', name: 'Jordan', area: 89342 },
  { iso: 'RS', name: 'Serbia', area: 88361 },
  { iso: 'AZ', name: 'Azerbaijan', area: 86600 },
  { iso: 'AE', name: 'United Arab Emirates', area: 83600 },
  { iso: 'AT', name: 'Austria', area: 83871 },
  { iso: 'CZ', name: 'Czech Republic', area: 78867 },
  { iso: 'PA', name: 'Panama', area: 75417 },
  { iso: 'SL', name: 'Sierra Leone', area: 71740 },
  { iso: 'IE', name: 'Ireland', area: 70273 },
  { iso: 'GE', name: 'Georgia', area: 69700 },
  { iso: 'LK', name: 'Sri Lanka', area: 65610 },
  { iso: 'LT', name: 'Lithuania', area: 65300 },
  { iso: 'LV', name: 'Latvia', area: 64559 },
  { iso: 'TG', name: 'Togo', area: 56785 },
  { iso: 'HR', name: 'Croatia', area: 56594 },
  { iso: 'BA', name: 'Bosnia and Herzegovina', area: 51209 },
  { iso: 'CR', name: 'Costa Rica', area: 51100 },
  { iso: 'SK', name: 'Slovakia', area: 49035 },
  { iso: 'DO', name: 'Dominican Republic', area: 48671 },
  { iso: 'EE', name: 'Estonia', area: 45227 },
  { iso: 'DK', name: 'Denmark', area: 43094 },
  { iso: 'NL', name: 'Netherlands', area: 41543 },
  { iso: 'CH', name: 'Switzerland', area: 41285 },
  { iso: 'BT', name: 'Bhutan', area: 38394 },
  { iso: 'TW', name: 'Taiwan', area: 36193 },
  { iso: 'GW', name: 'Guinea-Bissau', area: 36125 },
  { iso: 'BE', name: 'Belgium', area: 30528 },
  { iso: 'MD', name: 'Moldova', area: 33846 },
  { iso: 'LS', name: 'Lesotho', area: 30355 },
  { iso: 'AM', name: 'Armenia', area: 29743 },
  { iso: 'AL', name: 'Albania', area: 28748 },
  { iso: 'SB', name: 'Solomon Islands', area: 28896 },
  { iso: 'EH', name: 'Equatorial Guinea', area: 28051 },
  { iso: 'BI', name: 'Burundi', area: 27834 },
  { iso: 'HT', name: 'Haiti', area: 27750 },
  { iso: 'RW', name: 'Rwanda', area: 26338 },
  { iso: 'MK', name: 'North Macedonia', area: 25713 },
  { iso: 'DJ', name: 'Djibouti', area: 23200 },
  { iso: 'BZ', name: 'Belize', area: 22966 },
  { iso: 'IL', name: 'Israel', area: 20770 },
  { iso: 'SI', name: 'Slovenia', area: 20273 },
  { iso: 'FJ', name: 'Fiji', area: 18272 },
  { iso: 'KW', name: 'Kuwait', area: 17818 },
  { iso: 'SZ', name: 'Eswatini', area: 17364 },
  { iso: 'TL', name: 'East Timor', area: 14874 },
  { iso: 'BS', name: 'Bahamas', area: 13880 },
  { iso: 'VU', name: 'Vanuatu', area: 12189 },
  { iso: 'QA', name: 'Qatar', area: 11586 },
  { iso: 'JM', name: 'Jamaica', area: 10991 },
  { iso: 'LB', name: 'Lebanon', area: 10452 },
  { iso: 'CY', name: 'Cyprus', area: 9251 },
  { iso: 'PS', name: 'Palestine', area: 6020 },
  { iso: 'BN', name: 'Brunei', area: 5765 },
  { iso: 'TT', name: 'Trinidad and Tobago', area: 5130 },
  { iso: 'ME', name: 'Montenegro', area: 13812 },
  { iso: 'CV', name: 'Cape Verde', area: 4033 },
  { iso: 'LU', name: 'Luxembourg', area: 2586 },
  { iso: 'MU', name: 'Mauritius', area: 2040 },
  { iso: 'WS', name: 'Samoa', area: 2842 },
  { iso: 'KM', name: 'Comoros', area: 1862 },
  { iso: 'MV', name: 'Maldives', area: 298 },
  { iso: 'MT', name: 'Malta', area: 316 },
  { iso: 'ST', name: 'São Tomé and Príncipe', area: 964 },
  { iso: 'FM', name: 'Micronesia', area: 702 },
  { iso: 'TO', name: 'Tonga', area: 747 },
  { iso: 'KI', name: 'Kiribati', area: 811 },
  { iso: 'SG', name: 'Singapore', area: 710 },
  { iso: 'DM', name: 'Dominica', area: 751 },
  { iso: 'BH', name: 'Bahrain', area: 760 },
  { iso: 'LC', name: 'Saint Lucia', area: 616 },
  { iso: 'PW', name: 'Palau', area: 459 },
  { iso: 'SC', name: 'Seychelles', area: 452 },
  { iso: 'AD', name: 'Andorra', area: 468 },
  { iso: 'AG', name: 'Antigua and Barbuda', area: 442 },
  { iso: 'BB', name: 'Barbados', area: 430 },
  { iso: 'VC', name: 'Saint Vincent and the Grenadines', area: 389 },
  { iso: 'GD', name: 'Grenada', area: 344 },
  { iso: 'KN', name: 'Saint Kitts and Nevis', area: 261 },
  { iso: 'MH', name: 'Marshall Islands', area: 181 },
  { iso: 'LI', name: 'Liechtenstein', area: 160 },
  { iso: 'SM', name: 'San Marino', area: 61 },
  { iso: 'TV', name: 'Tuvalu', area: 26 },
  { iso: 'NR', name: 'Nauru', area: 21 },
  { iso: 'MC', name: 'Monaco', area: 2 },
  { iso: 'VA', name: 'Vatican City', area: 0.44 },
];

/**
 * Get country by ISO code
 */
export function getCountryByISO(iso: string): Country | undefined {
  return countriesBySize.find(c => c.iso === iso);
}

/**
 * Get country for ranking (1-194)
 * Ranking 1 = biggest country, ranking 194 = smallest country
 */
export function getCountryForRanking(ranking: number): Country | undefined {
  if (ranking < 1 || ranking > countriesBySize.length) return undefined;
  return countriesBySize[ranking - 1]; // 0-indexed array
}

/**
 * Get all countries sorted by size (largest to smallest)
 */
export function getAllCountriesSorted(): Country[] {
  return [...countriesBySize]; // Return copy
}
